name: Auto Update Google Alerts

on:
  workflow_dispatch:    # 手動觸發
  schedule:
    - cron: '0 */6 * * *'   # 每6小時執行一次

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests
      
      - name: Run Python Script
        run: python fetch_alerts.py
        continue-on-error: true
      
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "更新 Google Alerts $(date +%Y-%m-%d)" && git push)
